package LDTS.SpaceEscape.State;

public enum AppState {
    MENU_STATE, GAME_STATE, PAUSE_STATE, SCORE_STATE, GUIDE_STATE,
    GAME_OVER_STATE, LOAD_GAME_STATE, SAVE_GAME_STATE, BOSS_GAME_STATE,
    LEVEL_UP_GAME_STATE

}
